/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceConversionRouteImport } from './routes/voice-conversion'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveYoutubeRouteImport } from './routes/live-youtube'
import { Route as LiveTiktokRouteImport } from './routes/live-tiktok'
import { Route as LegendarRouteImport } from './routes/legendar'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CanvaCleanerRouteImport } from './routes/canva-cleaner'
import { Route as ApisRouteImport } from './routes/apis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoricoJobIdRouteImport } from './routes/historico.$jobId'
import { Route as ApiHubChavesRouteImport } from './routes/api-hub/chaves'

const VoiceConversionRoute = VoiceConversionRouteImport.update({
  id: '/voice-conversion',
  path: '/voice-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveYoutubeRoute = LiveYoutubeRouteImport.update({
  id: '/live-youtube',
  path: '/live-youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTiktokRoute = LiveTiktokRouteImport.update({
  id: '/live-tiktok',
  path: '/live-tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const LegendarRoute = LegendarRouteImport.update({
  id: '/legendar',
  path: '/legendar',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvaCleanerRoute = CanvaCleanerRouteImport.update({
  id: '/canva-cleaner',
  path: '/canva-cleaner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisRoute = ApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoJobIdRoute = HistoricoJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => HistoricoRoute,
} as any)
const ApiHubChavesRoute = ApiHubChavesRouteImport.update({
  id: '/api-hub/chaves',
  path: '/api-hub/chaves',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apis': typeof ApisRoute
  '/canva-cleaner': typeof CanvaCleanerRoute
  '/conta': typeof ContaRoute
  '/estudio': typeof EstudioRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/legendar': typeof LegendarRoute
  '/live-tiktok': typeof LiveTiktokRoute
  '/live-youtube': typeof LiveYoutubeRoute
  '/login': typeof LoginRoute
  '/radar': typeof RadarRoute
  '/recap': typeof RecapRoute
  '/tiktok': typeof TiktokRoute
  '/voice-conversion': typeof VoiceConversionRoute
  '/api-hub/chaves': typeof ApiHubChavesRoute
  '/historico/$jobId': typeof HistoricoJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apis': typeof ApisRoute
  '/canva-cleaner': typeof CanvaCleanerRoute
  '/conta': typeof ContaRoute
  '/estudio': typeof EstudioRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/legendar': typeof LegendarRoute
  '/live-tiktok': typeof LiveTiktokRoute
  '/live-youtube': typeof LiveYoutubeRoute
  '/login': typeof LoginRoute
  '/radar': typeof RadarRoute
  '/recap': typeof RecapRoute
  '/tiktok': typeof TiktokRoute
  '/voice-conversion': typeof VoiceConversionRoute
  '/api-hub/chaves': typeof ApiHubChavesRoute
  '/historico/$jobId': typeof HistoricoJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apis': typeof ApisRoute
  '/canva-cleaner': typeof CanvaCleanerRoute
  '/conta': typeof ContaRoute
  '/estudio': typeof EstudioRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/legendar': typeof LegendarRoute
  '/live-tiktok': typeof LiveTiktokRoute
  '/live-youtube': typeof LiveYoutubeRoute
  '/login': typeof LoginRoute
  '/radar': typeof RadarRoute
  '/recap': typeof RecapRoute
  '/tiktok': typeof TiktokRoute
  '/voice-conversion': typeof VoiceConversionRoute
  '/api-hub/chaves': typeof ApiHubChavesRoute
  '/historico/$jobId': typeof HistoricoJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apis'
    | '/canva-cleaner'
    | '/conta'
    | '/estudio'
    | '/historico'
    | '/legendar'
    | '/live-tiktok'
    | '/live-youtube'
    | '/login'
    | '/radar'
    | '/recap'
    | '/tiktok'
    | '/voice-conversion'
    | '/api-hub/chaves'
    | '/historico/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apis'
    | '/canva-cleaner'
    | '/conta'
    | '/estudio'
    | '/historico'
    | '/legendar'
    | '/live-tiktok'
    | '/live-youtube'
    | '/login'
    | '/radar'
    | '/recap'
    | '/tiktok'
    | '/voice-conversion'
    | '/api-hub/chaves'
    | '/historico/$jobId'
  id:
    | '__root__'
    | '/'
    | '/apis'
    | '/canva-cleaner'
    | '/conta'
    | '/estudio'
    | '/historico'
    | '/legendar'
    | '/live-tiktok'
    | '/live-youtube'
    | '/login'
    | '/radar'
    | '/recap'
    | '/tiktok'
    | '/voice-conversion'
    | '/api-hub/chaves'
    | '/historico/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApisRoute: typeof ApisRoute
  CanvaCleanerRoute: typeof CanvaCleanerRoute
  ContaRoute: typeof ContaRoute
  EstudioRoute: typeof EstudioRoute
  HistoricoRoute: typeof HistoricoRouteWithChildren
  LegendarRoute: typeof LegendarRoute
  LiveTiktokRoute: typeof LiveTiktokRoute
  LiveYoutubeRoute: typeof LiveYoutubeRoute
  LoginRoute: typeof LoginRoute
  RadarRoute: typeof RadarRoute
  RecapRoute: typeof RecapRoute
  TiktokRoute: typeof TiktokRoute
  VoiceConversionRoute: typeof VoiceConversionRoute
  ApiHubChavesRoute: typeof ApiHubChavesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-conversion': {
      id: '/voice-conversion'
      path: '/voice-conversion'
      fullPath: '/voice-conversion'
      preLoaderRoute: typeof VoiceConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-youtube': {
      id: '/live-youtube'
      path: '/live-youtube'
      fullPath: '/live-youtube'
      preLoaderRoute: typeof LiveYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-tiktok': {
      id: '/live-tiktok'
      path: '/live-tiktok'
      fullPath: '/live-tiktok'
      preLoaderRoute: typeof LiveTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legendar': {
      id: '/legendar'
      path: '/legendar'
      fullPath: '/legendar'
      preLoaderRoute: typeof LegendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canva-cleaner': {
      id: '/canva-cleaner'
      path: '/canva-cleaner'
      fullPath: '/canva-cleaner'
      preLoaderRoute: typeof CanvaCleanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis': {
      id: '/apis'
      path: '/apis'
      fullPath: '/apis'
      preLoaderRoute: typeof ApisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/$jobId': {
      id: '/historico/$jobId'
      path: '/$jobId'
      fullPath: '/historico/$jobId'
      preLoaderRoute: typeof HistoricoJobIdRouteImport
      parentRoute: typeof HistoricoRoute
    }
    '/api-hub/chaves': {
      id: '/api-hub/chaves'
      path: '/api-hub/chaves'
      fullPath: '/api-hub/chaves'
      preLoaderRoute: typeof ApiHubChavesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HistoricoRouteChildren {
  HistoricoJobIdRoute: typeof HistoricoJobIdRoute
}

const HistoricoRouteChildren: HistoricoRouteChildren = {
  HistoricoJobIdRoute: HistoricoJobIdRoute,
}

const HistoricoRouteWithChildren = HistoricoRoute._addFileChildren(
  HistoricoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApisRoute: ApisRoute,
  CanvaCleanerRoute: CanvaCleanerRoute,
  ContaRoute: ContaRoute,
  EstudioRoute: EstudioRoute,
  HistoricoRoute: HistoricoRouteWithChildren,
  LegendarRoute: LegendarRoute,
  LiveTiktokRoute: LiveTiktokRoute,
  LiveYoutubeRoute: LiveYoutubeRoute,
  LoginRoute: LoginRoute,
  RadarRoute: RadarRoute,
  RecapRoute: RecapRoute,
  TiktokRoute: TiktokRoute,
  VoiceConversionRoute: VoiceConversionRoute,
  ApiHubChavesRoute: ApiHubChavesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
